pynata/cards/urls.py
from django.urls import path

from . import views

app_name = 'cards'

urlpatterns = [
    path('', views.index, name='main_page'),
    # path('card/', views.card_list, name='card_list'),
    path('card/<int:card_id>/', views.card_detail, name='card_detail'),
    path('card/<int:card_id>/feedback/',
         views.add_feedback, name='add_feedback'),
]

pynata/pynata/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('cards.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

pynata/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logout.html'),
        name='logout'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'),
]

pynata/cards/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

MAX_TEXT_LEN: int = 15

TYPE_OF_SIZES: tuple = (
    ('S', 'S'),
    ('M', 'M'),
    ('L', 'L'),
    ('Xl', 'XL'),
)

TYPE_OF_PYNATA: tuple = (
    ('Circle', 'Круглая'),
    ('Shield', 'Щит'),
    ('Figure', 'Фигурная'),
)

RATINGS = (
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5)
)


class Filling(models.Model):
    """Наполнение Пиньяты."""
    name = models.CharField(max_length=50, help_text='Наименование')
    description = models.TextField(help_text='Описание')
    size_type = models.CharField(choices=TYPE_OF_SIZES, max_length=50, help_text='Тип наполнения')
    weigth = models.IntegerField(help_text='Вес в гр.')
    cost = models.IntegerField(help_text='Цена')
    image = models.ImageField(
        upload_to='card/',
        help_text='Картинка',
    )

    def __str__(self):
        return self.name


class Card(models.Model):
    """Карточка Пиньяты."""
    name = models.CharField(max_length=50, help_text='Наименование')
    description = models.TextField(help_text='Описание')
    pynata_type = models.CharField(choices=TYPE_OF_PYNATA, max_length=50, help_text='Форма')
    size_type = models.CharField(choices=TYPE_OF_SIZES, max_length=50, help_text='Размер')
    cost = models.IntegerField(help_text='Цена')
    filling = models.ForeignKey(
        Filling,
        null=True,
        help_text='Наполнение',
        on_delete=models.CASCADE,
        related_name='cards',
    )
    image = models.ImageField(
        upload_to='card/',
        help_text='Картинка',
    )

    def __str__(self):
        return self.name[:MAX_TEXT_LEN]


class Service(models.Model):
    """Карточка услуги."""
    name = models.CharField(max_length=50, help_text='Наименование')
    cost = models.IntegerField(help_text='Цена')
    image = models.ImageField(
        upload_to='card/',
        help_text='Картинка',
    )

    def __str__(self):
        return self.name[:MAX_TEXT_LEN]


class Feedback(models.Model):
    """Отзывы."""
    card = models.ForeignKey(
        Card,
        blank=True,
        null=False,
        on_delete=models.CASCADE,
        related_name='feedbacks',
        help_text='Карточка товара'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        related_name='feedbacks',
        help_text='Пользователь'
    )
    text = models.TextField(help_text='Текст отзыва')
    rating = models.IntegerField(
        choices=RATINGS,
        null=True,
        help_text='Рейтинг'
    )
    created = models.DateTimeField(auto_now_add=True, help_text='Дата отзыва')

    def __str__(self):
        return f'{self.author}: {self.text[:MAX_TEXT_LEN]}'

pynata/cart/models.py
from django.db import models
from cards.models import Card


class Cart(models.Model):
    cart_id = models.CharField(max_length=25)
    date_added = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(default=1)
    product = models.ForeignKey(Card, unique=False)

    class Meta:
        ordering = ['date_added']

pynata/core/models.py
from django.db import models

# Create your models here.

pynata/cards/forms.py
from django import forms
from .models import Feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ('text', 'rating', )

pynata/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

pynata/cards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Avg
from .models import Card
from .forms import FeedbackForm


def index(request):
    template = 'index.html'
    cards = Card.objects.all()
    context = {
        'cards': cards,
    }
    return render(request, template, context)


def card_detail(request, card_id):
    card = get_object_or_404(Card, id=card_id)
    rating = Card.objects.annotate(
        rating=Avg('feedbacks__rating')).get(pk=card_id).rating
    feedback_form = FeedbackForm()
    context = {
        'card': card,
        'feedback_form': feedback_form,
        'feedbacks': card.feedbacks.all(),
        'rating': round(rating, 1)
    }
    return render(request, 'cards/card_detail.html', context)


@login_required
def add_feedback(request, card_id):
    card = get_object_or_404(Card, id=card_id)
    form = FeedbackForm(request.POST or None)
    if form.is_valid():
        feedback = form.save(commit=False)
        feedback.author = request.user
        feedback.card = card
        feedback.save()
    return redirect('cards:card_detail', card_id=card_id)

pynata/cart/views.py
from django.shortcuts import render

# Create your views here.

pynata/core/views.py
from django.shortcuts import render

# Create your views here.

pynata/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm
from django.core.mail import send_mail


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('cards:main_page')
    template_name = 'users/signup.html'


send_mail(
    'Тема письма',
    'Текст письма.',
    'from@example.com',
    ['to@example.com'],
    fail_silently=False,
)

pynata/templates/base.html
{% load static %}
<html lang="ru" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
      Онлайн-магазин пиньят Yarpinata
      {% endblock %}
    </title>
    <header>
      {% include 'includes/header.html' %}
    </header>
    {% include 'includes/api_and_adv.html' %}
  </head>
  <body style="background-color: WhiteSmoke">
    <div class="container py-6">
    <h1> Магазин Пиньят </h1>
    <main>
      {% block content %}
      Где контент то?
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
  </div>
  </body>
</html>

pynata/templates/cards/card_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}
{{ card.text|truncatechars:30 }}
{% endblock %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <h5>Название: {{ card.name }}</h5>
      </li>
      <li class="list-group-item">
        <h5>Размер: {{ card.size_type }}</h5>
      </li>
      <li class="list-group-item">
        <h5>Цена: {{ card.cost }} руб.</h5>
      </li>
      <li class="list-group-item">
        <h5>Вес: {{ card.filling.weigth }} гр.</h5>
      </li>
      <li class="list-group-item">
        <h5>Рейтинг: {{ rating }}</h5>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    {% thumbnail card.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>Описание: {{ card.description }}</p>
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить отзыв:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'cards:add_feedback' card.id %}">
        {% csrf_token %}
          {{ feedback_form.text|addclass:"form-control" }}
          <h5 class="card-header">Оценка:</h5>
          {{ feedback_form.rating|addclass:"form-check" }}
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% for feedback in feedbacks %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        {{ feedback.author.username }}
      </h5>
      <p>
        {{ feedback.text }}
      </p>
      <p>
        {{ feedback.rating }}
      </p>
    </div>
  </div>
{% endfor %}
  </article>
</div>
{% endblock %}

pynata/templates/cards/card_post.html
{% load thumbnail %}
{% for card in cards %}
<ul>
    <li>
        Название: {{ card.name }}
    </li>
    <li>
        <b> Цена: {{ card.cost }} руб. </b>
    </li>
    <li>
        <a href="{% url 'cards:card_detail' card.id %}">Подробная информация</a>
    </li>
    {% thumbnail card.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    </ul>
{% endfor %}

pynata/templates/includes/api_and_adv.html
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-3" style="color: black; font-size: 20px">
          <a href="https://yandex.ru/pogoda/16?lat=57.626559&lon=39.893813">
            <img src="{% static 'img/yandex-weather.svg' %}" class="rounded float-left">
          </a>
          Ярославль: {{ weather.temperature }} ℃, {{ weather.condition }}
          <img src="https://yastatic.net/weather/i/icons/funky/dark/{{weather.icon}}.svg">
        </div>
        <div class="col-8">
          <marquee scrollamount="10" style="color: lightskyblue;
           font-size: 40px; font-weight: bolder;
           line-height: 150%;
           text-shadow: #000000 0px 1px 1px;">
            Акция! При заказе Пиньяты и наполнения XL, доставка и палка - в подарок !
          </marquee>
        </div>
      </div>
    </div>

pynata/templates/includes/footer.html
{% load static %}
<footer class="border-top text-center py-3">
  <p>
    <h4>{% now 'Y' %} г. <span style="color:#C71585"><b> YarPinata © </b></span>
    </h4>
    <a href="https://vk.com/yarpinata">
      <img src="{% static 'img/vk.png' %}" width="40" height="40" class="d-inline-block align-top">
    </a>
  </p>
</footer>

pynata/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'cards:main_page' %}">
      <img src="{% static 'img/logo.png' %}" width="40" height="40" class="d-inline-block align-top" alt="">
      <span style="color:#C71585"><b>YarPinata</b></span>
    </a>
    <ul class="nav nav-pills">
      <li class="nav-item">
        <h5><a class="nav-link" style="color: black"> О нас </a></h5>
      <li class="nav-item">
      <li class="nav-item">
        <h5><a class="nav-link" style="color: black"> Оплата и доставка </a></h5>
      <li class="nav-item">
      <li class="nav-item">
        <h5><a class="nav-link" style="color: black"> Новости и акции </a></h5>
      <li class="nav-item">
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <h5><a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}" style="color: black"
           href="{% url 'users:logout' %}">Выйти</a></h5>
      </li>
      <li class="nav-link" style="color: black">
        <h5><p><b>Пользователь: {{ user.username }}</b></p></h5>
      </li>
      {% else %}
      <ul class="nav nav-pills">
      <li class="nav-item">
        <h5><a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" style="color: black"
           href="{% url 'users:login' %}">Войти</a></h5>
      </li>
      <li class="nav-item">
        <h5><a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" style="color: black"
           href="{% url 'users:signup' %}">Регистрация</a></h5>
      </li>
      {% endif %}
      <li class="nav-item">
        <h5><a class="nav-link" style="color: black"> Корзина </a></h5>
      <li class="nav-item">
    </ul>
  </ul>
  </div>
</nav>

pynata/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% block content %}
{% include 'cards/card_post.html' %}
{% endblock %}

pynata/templates/users/login.html
{% extends "index.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %} 

pynata/templates/users/logout.html
{% extends 'index.html' %}
{% block title %}
Вы вышли из системы
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

pynata/templates/users/signup.html
{% extends "index.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}